title: "Ron Rochwerg"
description: "PhD Student, Computer Science, Queen's University"
baseurl: ""           # No subdirectory, as this is hosted at your root GitHub Pages site
url: "https://ron-rochwerg.github.io"

theme: cvless
# remote_theme: piazzai/cvless

# site settings
taglong: "Academic Portfolio of Ron Rochwerg"
tagshort: "Academic CV"
cv: true              # Ensure the CV page is enabled

# author settings
author:
  name: "Ron Rochwerg"
  email: "17rer6@queensu.ca"
photo: assets/files/Headshot.jpg   # Put your profile image here if using one (optional)
joblines:
  - "Queen's University, Ph.D. Candidate"
  - "Department of Computer Science"
  - "Kingston, ON, Canada"
address: "Queen's University, Kingston, ON"
phone: ""                     # Leave blank if you prefer not to share

# profile links
profile:
  linkedin: "https://www.linkedin.com/in/ron-rochwerg"
  github: "https://github.com/ronrochwerg"
  miblab: "https://sites.google.com/site/tinghushomepage"
  mulab: "https://mulab.ai/"
  # google_scholar: "https://scholar.google.com/your-profile"  # Add if you have a Google Scholar link

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
